pr1 = PrivateKey(100)
# print(pr1.point.address(compressed=False,testnet=True))
# pr2 = PrivateKey(2020**5)
# print(pr2.point.address(compressed=True, testnet=True))
# pr3 = PrivateKey(0x12345deadbeef)
# print(pr3.point.address(compressed=True, testnet=False))